### PR TITLE
Fix analysis for new *.sol files

### PR DESCRIPTION
**Pull request by daniyarchambylov**
This fixes cases when new solidity files added to `contracts` directory after analysis have been run on existing ones in the project.

### CODE REVIEW

**Comment by nbanmp** [comment]
With this PR, when I create a new file in the `contracts/` directory, it exits immediately after compiling.

```
$ ls contracts
bad_constructor2.sol  integer_overflow_mul.sol  old_blockhash.sol
bad_constructor.sol   Migrations.sol            suicide_multitx_feasible.sol
$ truffle run verify
Compiling ./contracts/bad_constructor2.sol...
/home/nat/Dev/mythx/vulnerable_truffle_project/contracts/bad_constructor2.sol
$ 
```

**Comment by daniyarchambylov** [comment]
@nbanmp I've merged master into this PR and rewrote for loop to Promise.all and async map

**Comment by nbanmp** [comment]
It now successfully analyzes new *.sol files.

However, when a *.sol is deleted, the contracts that were in it are still analyzed. This is probably in the same block of code and is a very similar issue, so fixing that at the same time is probably the right thing to do. WDYT?

**Comment by daniyarchambylov** [comment]
Added  fix to skip analyze for removed contracts

**Pull request merged**
