### PR TITLE
[MI-15] integration tests

### PR DESCRIPTION
**Pull request by fgimenez**
Adds a simple truffle project and checks that the plugin returns three expected issues. It connects to production if a tag is present, staging if not (so, staging for PRs).

### CODE REVIEW

**Comment by rocky** [comment]
I _definitely_ like the idea - thanks! (I also am slow at looking at code but am a geek at heart so I want to try this, I hope, today.)

**Comment by rocky** [comment]
@fgimenez Probably can wait until the pending release is out, right?

**Comment by fgimenez** [comment]
Sure, as you see fit.

**Comment by daniyarchambylov** [comment]
Cool! Looking forward to have it running. thanks  @fgimenez!

**Comment by fgimenez** [comment]
> In the near future I think we will resolve why/how it is failing.

@rocky It fails because of MBT-80, we need the complete `sourceList` in the input, with it in place the integration test passes.

**Comment by fgimenez** [comment]
stale, will reopen

**Pull request closed without merging**
