### PR TITLE
Add a markdown eslint formatter

### PR DESCRIPTION
**Pull request by nbanmp**
Add markdown formatting with https://www.npmjs.com/package/eslint-formatter-markdown

### CODE REVIEW

**Comment by nbanmp** [comment]
There's something I want to improve with the formatting, I'm not too happy with the default formatter, give me a bit to fix that up, then we can merge this.

**Comment by nbanmp** [comment]
All improved now, review when ready.

**Comment by daniyarchambylov** [comment]
That would be cool to have truffle-security generate markdown report similar to what `vscode-solidity` has been doing. Unfortunately we didn't get chance to port it o truffle-security. 
I've attached sample Markdown file inside zip to look at. WDYT?
[SimpleDAO-1548334084459.zip](https://github.com/ConsenSys/truffle-security/files/3222152/SimpleDAO-1548334084459.zip)

**Comment by PaulRBerg** [comment]
This would be a wonderful feature to add! I resorted it to HTML in the meantime but I'd always choose Markdown over that.

**Comment by nbanmp** [comment]
@daniyarchambylov I'll look into using the same format as vscode-solidity.

**Pull request merged**
